### PR TITLE
Reduce load on API in EnvironmentsController#index

### PR DESCRIPTION
**Pull request by EdwardAndress**
- Store data in new cols on Environments table
- Check when the data was collected last
- Call api if Environment#interval minutes has passed since last update

### CODE REVIEW

**Comment by himal-mandalia** [comment]
@EdwardAndress looks good - have migrated and run it locally. Maybe we should update this copy on the dashboard:

"Reload this page to ensure the information is up to date – it does not refresh automatically"

Show a last updated and a message to say it may be up to 10 minutes stale.

**Comment by EdwardAndress** [comment]
@himal-mandalia - good call!  I will do that later on today.

**Comment by himal-mandalia** [comment]
@EdwardAndress slightly unrelated, but the environments should probably be ordered by name on the dashboard.

**Comment by himal-mandalia** [comment]
@EdwardAndress in addition to reducing the polling frequency by caching the result every 10 minutes, we should also look at handling environments which timeout (502). This can cause the dashboard to wait/lock for up to 10 seconds. These calls could be made asynchronously or we could impose a smaller timeout on the client (our) side, i.e. 2 seconds.

**Review by himal-mandalia — APPROVED** [review]
Looks good

**Comment by EdwardAndress** [comment]
[Reduce the load that the Environments#index view places on the API.](https://trello.com/c/HVPUCviz/560-reduce-the-load-that-the-environmentsindex-view-places-on-the-api)

**Pull request merged**
